services:
  - type: web
    name: ecommerce-flask-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: STRIPE_SECRET_KEY
        sync: false
